In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/data7/deepro/starrseq/4_ml_classification_fragment_category/data/CC/linear/homer/motif_odds.tsv", sep="\t")

In [6]:
df.loc[df.PositionID=="chr22_25061458_25062458"].sort_values("MotifScore", ascending=False).head(60)

,PositionID,Offset,Sequence,Motif Name,Strand,MotifScore
52720644,chr22_25061458_25062458,687,GATCCTCCCACCTCAGCCTCGT,ZN770_HUMAN.H11MO.0.C,-,17.087337
50779309,chr22_25061458_25062458,754,CCTCTTCCTCCTCCTCTTCCCC,ZN467_HUMAN.H11MO.0.C,-,16.265723
50779303,chr22_25061458_25062458,760,CCTCCTCCTCTTCCCCCTCCTT,ZN467_HUMAN.H11MO.0.C,-,15.840667
50779374,chr22_25061458_25062458,486,CTTCCTTCTTTTCCTCCTCCCT,ZN467_HUMAN.H11MO.0.C,-,15.149286
43854209,chr22_25061458_25062458,750,CTCCTCTTCCTCCTCCTCTT,WT1_HUMAN.H11MO.0.C,-,14.733670
47828020,chr22_25061458_25062458,485,TTCCTTCTTTTCCTCCTCCC,ZN263_HUMAN.H11MO.0.A,-,14.579874
50779363,chr22_25061458_25062458,501,CCTCCCTTTTCTCTTCCTCCCT,ZN467_HUMAN.H11MO.0.C,-,14.433087
47827987,chr22_25061458_25062458,747,CATCTCCTCTTCCTCCTCCT,ZN263_HUMAN.H11MO.0.A,-,14.383994
47827962,chr22_25061458_25062458,829,TTCTTCTTCCTCCTCCTCCT,ZN263_HUMAN.H11MO.0.A,-,14.337333
46981974,chr22_25061458_25062458,638,GGTCTGGCCATGTTGCCAAG,ZN121_HUMAN.H11MO.0.C,-,14.321275
43285810,chr22_25061458_25062458,755,CTCTTCCTCCTCCTCTTCCCCC,VEZF1_HUMAN.H11MO.0.C,-,14.264790
47827985,chr22_25061458_25062458,753,CTCTTCCTCCTCCTCTTCCC,ZN263_HUMAN.H11MO.0.A,-,14.221733
50779354,chr22_25061458_25062458,513,CTTCCTCCCTCTTCTCTTCCTC,ZN467_HUMAN.H11MO.0.C,-,14.145725
43285813,chr22_25061458_25062458,752,CTCCTCTTCCTCCTCCTCTTCC,VEZF1_HUMAN.H11MO.0.C,-,14.134108
50779278,chr22_25061458_25062458,802,CTTCCTCTCTTTTCTCCTCCTC,ZN467_HUMAN.H11MO.0.C,-,14.117102
50779323,chr22_25061458_25062458,582,CTTCCTCCCTTTTCTCCTCCTT,ZN467_HUMAN.H11MO.0.C,-,14.114093
49507695,chr22_25061458_25062458,754,CCTCTTCCTCCTCCTCTTCCCC,ZN341_HUMAN.H11MO.0.C,-,14.096605
47827983,chr22_25061458_25062458,759,CTCCTCCTCTTCCCCCTCCT,ZN263_HUMAN.H11MO.0.A,-,14.008113
21724460,chr22_25061458_25062458,831,TTCTTCTTCCTCCTCCTCCTCC,MAZ_HUMAN.H11MO.0.A,-,14.002032
47827961,chr22_25061458_25062458,832,TTCTTCCTCCTCCTCCTCCA,ZN263_HUMAN.H11MO.0.A,-,13.948405
50779366,chr22_25061458_25062458,498,CCTCCTCCCTTTTCTCTTCCTC,ZN467_HUMAN.H11MO.0.C,-,13.817902
50779260,chr22_25061458_25062458,830,TTTCTTCTTCCTCCTCCTCCTC,ZN467_HUMAN.H11MO.0.C,-,13.810942
21724568,chr22_25061458_25062458,502,CTCCCTTTTCTCTTCCTCCCTC,MAZ_HUMAN.H11MO.0.A,-,13.712631
29059963,chr22_25061458_25062458,754,CCTCTTCCTCCTCCTCTTCCCC,PATZ1_HUMAN.H11MO.0.C,-,13.687667
21724505,chr22_25061458_25062458,761,CTCCTCCTCTTCCCCCTCCTTT,MAZ_HUMAN.H11MO.0.A,-,13.672535
43854204,chr22_25061458_25062458,759,CTCCTCCTCTTCCCCCTCCT,WT1_HUMAN.H11MO.0.C,-,13.663553
49507688,chr22_25061458_25062458,766,CCTCTTCCCCCTCCTTTTCCTC,ZN341_HUMAN.H11MO.0.C,-,13.601104
50779276,chr22_25061458_25062458,805,CCTCTCTTTTCTCCTCCTCCTC,ZN467_HUMAN.H11MO.0.C,-,13.549027
43285805,chr22_25061458_25062458,761,CTCCTCCTCTTCCCCCTCCTTT,VEZF1_HUMAN.H11MO.0.C,-,13.515888
43285859,chr22_25061458_25062458,508,TTTCTCTTCCTCCCTCTTCTCT,VEZF1_HUMAN.H11MO.0.C,-,13.474492
43854208,chr22_25061458_25062458,753,CTCTTCCTCCTCCTCTTCCC,WT1_HUMAN.H11MO.0.C,-,13.399587
47827963,chr22_25061458_25062458,826,TTTTTCTTCTTCCTCCTCCT,ZN263_HUMAN.H11MO.0.A,-,13.377821
18373007,chr22_25061458_25062458,760,CCTCCTCTTCCCCCTCCTT,KLF15_HUMAN.H11MO.0.A,-,13.373012
18373020,chr22_25061458_25062458,582,CCTCCCTTTTCTCCTCCTT,KLF15_HUMAN.H11MO.0.A,-,13.327438
50779293,chr22_25061458_25062458,772,CCCCCTCCTTTTCCTCTTCCAC,ZN467_HUMAN.H11MO.0.C,-,13.292605
43285763,chr22_25061458_25062458,831,TTCTTCTTCCTCCTCCTCCTCC,VEZF1_HUMAN.H11MO.0.C,-,13.287537
28053825,chr22_25061458_25062458,385,CCCTGCGCATGCCCAGG,NRF1_HUMAN.H11MO.0.A,+,13.252297
21724514,chr22_25061458_25062458,752,CTCCTCTTCCTCCTCCTCTTCC,MAZ_HUMAN.H11MO.0.A,-,13.144868
43285807,chr22_25061458_25062458,758,TTCCTCCTCCTCTTCCCCCTCC,VEZF1_HUMAN.H11MO.0.C,-,13.106820
18372993,chr22_25061458_25062458,802,CCTCTCTTTTCTCCTCCTC,KLF15_HUMAN.H11MO.0.A,-,13.078463
21724511,chr22_25061458_25062458,755,CTCTTCCTCCTCCTCTTCCCCC,MAZ_HUMAN.H11MO.0.A,-,13.077566
21724477,chr22_25061458_25062458,806,CTCTCTTTTCTCCTCCTCCTCT,MAZ_HUMAN.H11MO.0.A,-,13.056958
43285799,chr22_25061458_25062458,767,CTCTTCCCCCTCCTTTTCCTCT,VEZF1_HUMAN.H11MO.0.C,-,12.922150
52553903,chr22_25061458_25062458,190,GAGGCACAGAGAAGAGAAGC,ZN768_HUMAN.H11MO.0.C,+,12.911306
43285870,chr22_25061458_25062458,493,CTTTTCCTCCTCCCTTTTCTCT,VEZF1_HUMAN.H11MO.0.C,-,12.864178
50779313,chr22_25061458_25062458,748,CCATCTCCTCTTCCTCCTCCTC,ZN467_HUMAN.H11MO.0.C,-,12.858743
49507731,chr22_25061458_25062458,510,TCTCTTCCTCCCTCTTCTCTTC,ZN341_HUMAN.H11MO.0.C,-,12.789028
38149276,chr22_25061458_25062458,476,CTCCACTTCCTTCTTTT,SPI1_HUMAN.H11MO.0.A,-,12.756625
49507711,chr22_25061458_25062458,579,TCTCTTCCTCCCTTTTCTCCTC,ZN341_HUMAN.H11MO.0.C,-,12.750947
29059959,chr22_25061458_25062458,760,CCTCCTCCTCTTCCCCCTCCTT,PATZ1_HUMAN.H11MO.0.C,-,12.746251
43854177,chr22_25061458_25062458,829,TTCTTCTTCCTCCTCCTCCT,WT1_HUMAN.H11MO.0.C,-,12.745280
18373014,chr22_25061458_25062458,748,TCTCCTCTTCCTCCTCCTC,KLF15_HUMAN.H11MO.0.A,-,12.707319
43285879,chr22_25061458_25062458,478,CTTCTCCACTTCCTTCTTTTCC,VEZF1_HUMAN.H11MO.0.C,-,12.573663
38302508,chr22_25061458_25062458,476,CTCCACTTCCTTCTTTT,SPIB_HUMAN.H11MO.0.A,-,12.558277
43285775,chr22_25061458_25062458,812,TTTCTCCTCCTCCTCTTTTTTC,VEZF1_HUMAN.H11MO.0.C,-,12.547550
43854176,chr22_25061458_25062458,832,TTCTTCCTCCTCCTCCTCCA,WT1_HUMAN.H11MO.0.C,-,12.401268
50779296,chr22_25061458_25062458,769,CTTCCCCCTCCTTTTCCTCTTC,ZN467_HUMAN.H11MO.0.C,-,12.375301
21724480,chr22_25061458_25062458,803,TTCCTCTCTTTTCTCCTCCTCC,MAZ_HUMAN.H11MO.0.A,-,12.365182
28754535,chr22_25061458_25062458,389,GCGCATGCCCAGGCAAGACC,P53_HUMAN.H11MO.0.A,+,12.358088
50779311,chr22_25061458_25062458,751,TCTCCTCTTCCTCCTCCTCTTC,ZN467_HUMAN.H11MO.0.C,-,12.337349

In [6]:
df

,PositionID,Offset,Sequence,Motif Name,Strand,MotifScore
0,chrX_154800144_154801144,24,TTTGCATGG,AHR_HUMAN.H11MO.0.B,+,3.842687
1,chrX_154800144_154801144,331,ACATGCAAA,AHR_HUMAN.H11MO.0.B,-,4.355972
2,chrX_154800144_154801144,14,GCTCGCAAA,AHR_HUMAN.H11MO.0.B,-,3.886547
3,chrX_154800044_154801044,124,TTTGCATGG,AHR_HUMAN.H11MO.0.B,+,3.842687
4,chrX_154800044_154801044,431,ACATGCAAA,AHR_HUMAN.H11MO.0.B,-,4.355972
...,...,...,...,...,...,...
54192173,chr1_910305_911305,944,GGCAGCACGGCGATCACC,ZSC31_HUMAN.H11MO.0.C,+,6.758951
54192174,chr1_910305_911305,832,CCTCCCCGCCCCACTGTG,ZSC31_HUMAN.H11MO.0.C,-,4.317204
54192175,chr1_910305_911305,544,GAGGCCGGCACTGCTGAA,ZSC31_HUMAN.H11MO.0.C,-,5.944679
54192176,chr1_910305_911305,459,AAACCCAGCCCTGCCGCT,ZSC31_HUMAN.H11MO.0.C,-,7.244507
54192177,chr1_910305_911305,387,CGTGCCCGCCAGGCTGCC,ZSC31_HUMAN.H11MO.0.C,-,4.886490